spring:
  application:
    name: staylog
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      local:
        - common
        - private-local
      dev:
        - common
        - private-dev