server:
  port: 9000
# =====================================
# Oracle Database Connection Settings
# =====================================
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@54.180.94.201:1521:xe
    username: team404f
    password: 4041234
# =====================================
# Email 인증
# 이메일, 시크릿 키
# =====================================
  mail: 
    username: kasious84@gmail.com
    password: ryfb pybk hxmr xvpq


# =====================================
# JWT Token Settings
# JWT secret key
# =====================================
jwt:
  secret: eW91ci1zdXBlci1zZWNyZXQta2V5LTEyMzQ1Njc4OTAhQCMkJV4mKigpXystPVtde318OzosLjw+Pw==