spring:
# =====================================
# Connection Pool (HikariCP) Settings
# =====================================
# 동시에 유지할 최대 커넥션 수
# 최소 유지 커넥션 수
# 유휴 커넥션이 닫히기 전까지의 시간(ms)
# 커넥션의 최대 생존 시간(ms)
# 커넥션을 얻을 때 대기 최대 시간(ms)
# HikariCP 커넥션 풀의 이름을 지정
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      pool-name: StaylogHikariCP

  # https 관련 오류 수정
  security:
    filter:
      dispatcher-types: 
        - REQUEST
        - ERROR
# =====================================
# Email 인증
# =====================================
  mail:
    host: smtp.gmail.com
    port: 587
    properties: 
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true 


# =====================================
# UTF-8 Encoding Settings
# =====================================
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # https 신뢰
  forward-headers-strategy: framework

# =====================================
# Mybatis Settings
# =====================================
# mybatis 에서 사용하는 xml 문서가 어디에 있는지 알려주기
# classpath: 는 resources 폴더를 가리킨다.
# type 에 별칭을 붙인 클래스를 찾아서 로딩하기 위해
# com.staylog.staylog. 하위 패키지에서 모든 @Alias 가 붙은 클래스를 찾아서 사용할 준비를 한다
mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml
  type-aliases-package: com.staylog.staylog.**
  configuration:
    map-underscore-to-camel-case: true


# =====================================
# JWT Token Settings
# =====================================
jwt:
  access-token-validity: 3600000
  refresh-token-validity: 1209600000
  issuer: staylog
  cookie:
    refresh-token-name: refreshToken
    http-only: true
    secure: false
    domain: localhost
    path: /


# =====================================
# Swagger UI
# =====================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html









